/* =========================================================
   COMPASS CAMPUS - SCHEMA-5B DATA KAMPUS REALISTIS

   Fungsi file:
   1. Menambah seed kampus ternama Indonesia untuk demo.
   2. Menambah seed program studi populer lintas bidang.
   3. Memperbarui data jika slug sudah ada.
   4. Data ini bukan hasil verifikasi final. Akreditasi wajib dicek ulang
      lewat PDDikti, BAN-PT/LAM, dan website resmi kampus.
   ========================================================= */

USE help_desk_comcam;

CREATE TABLE IF NOT EXISTS campuses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    slug VARCHAR(120) NOT NULL,
    campus_name VARCHAR(160) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address VARCHAR(255) DEFAULT NULL,
    website VARCHAR(180) DEFAULT NULL,
    campus_type VARCHAR(100) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_campuses_slug (slug)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS study_programs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campus_id BIGINT UNSIGNED NOT NULL,
    slug VARCHAR(120) NOT NULL,
    program_name VARCHAR(160) NOT NULL,
    faculty VARCHAR(160) NOT NULL,
    degree VARCHAR(40) NOT NULL DEFAULT 'S1',
    accreditation VARCHAR(80) DEFAULT 'Dalam pendataan',
    learning_mode VARCHAR(80) DEFAULT 'Reguler',
    duration VARCHAR(80) DEFAULT '8 Semester',
    tuition_range VARCHAR(180) DEFAULT NULL,
    summary TEXT NOT NULL,
    curriculum_points TEXT DEFAULT NULL,
    career_paths TEXT DEFAULT NULL,
    skills TEXT DEFAULT NULL,
    facilities TEXT DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_study_programs_slug (slug),
    INDEX idx_study_programs_campus_id (campus_id),
    INDEX idx_study_programs_faculty (faculty),
    INDEX idx_study_programs_active (is_active),
    CONSTRAINT fk_study_programs_campus FOREIGN KEY (campus_id) REFERENCES campuses(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO campuses (id, slug, campus_name, city, address, website, campus_type, description)
VALUES
    (1, 'universitas-esa-unggul', 'Universitas Esa Unggul', 'Jakarta dan Bekasi', 'Jakarta Barat dan Harapan Indah Bekasi', 'https://www.esaunggul.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta dengan pilihan program studi lintas bidang. Data ini dipakai sebagai seed awal ComCam dan perlu diverifikasi kembali dengan sumber resmi kampus.'),
    (2, 'universitas-indonesia', 'Universitas Indonesia', 'Depok dan Jakarta', 'Depok, Jawa Barat dan Salemba, Jakarta', 'https://www.ui.ac.id', 'Perguruan Tinggi Negeri', 'Perguruan tinggi negeri besar di Indonesia dengan program lintas rumpun ilmu. Data ringkas ini digunakan untuk simulasi direktori awal.'),
    (3, 'institut-teknologi-bandung', 'Institut Teknologi Bandung', 'Bandung', 'Bandung, Jawa Barat', 'https://www.itb.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri yang dikenal kuat pada bidang sains, teknologi, seni, desain, dan rekayasa. Data ini bersifat seed awal untuk demo ComCam.'),
    (4, 'universitas-gadjah-mada', 'Universitas Gadjah Mada', 'Yogyakarta', 'Sleman, Daerah Istimewa Yogyakarta', 'https://www.ugm.ac.id', 'Perguruan Tinggi Negeri', 'Perguruan tinggi negeri besar di Yogyakarta dengan pilihan program studi luas. Data ini perlu diverifikasi sebelum dipakai sebagai informasi final.'),
    (5, 'institut-pertanian-bogor', 'IPB University', 'Bogor', 'Dramaga, Bogor, Jawa Barat', 'https://www.ipb.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri yang kuat pada rumpun pertanian, pangan, biosains, bisnis, dan teknologi terapan. Data ini adalah seed awal ComCam.'),
    (6, 'institut-teknologi-sepuluh-nopember', 'Institut Teknologi Sepuluh Nopember', 'Surabaya', 'Sukolilo, Surabaya, Jawa Timur', 'https://www.its.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri berbasis teknologi, sains, maritim, sistem informasi, dan rekayasa. Data disiapkan untuk demo realistis.'),
    (7, 'universitas-airlangga', 'Universitas Airlangga', 'Surabaya', 'Surabaya, Jawa Timur', 'https://www.unair.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri dengan kekuatan pada kesehatan, sosial, ekonomi, dan sains. Data awal ini perlu dicocokkan dengan sumber resmi.'),
    (8, 'universitas-diponegoro', 'Universitas Diponegoro', 'Semarang', 'Tembalang, Semarang, Jawa Tengah', 'https://www.undip.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri di Semarang dengan beragam program studi sains, sosial, ekonomi, dan teknik. Data ini untuk kebutuhan simulasi.'),
    (9, 'universitas-brawijaya', 'Universitas Brawijaya', 'Malang', 'Malang, Jawa Timur', 'https://www.ub.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri di Malang dengan pilihan program studi luas pada sosial, ekonomi, teknologi, kesehatan, dan pertanian.'),
    (10, 'universitas-padjadjaran', 'Universitas Padjadjaran', 'Bandung dan Sumedang', 'Jatinangor, Sumedang dan Bandung, Jawa Barat', 'https://www.unpad.ac.id', 'Perguruan Tinggi Negeri', 'Kampus negeri di Jawa Barat dengan rumpun sosial, kesehatan, hukum, komunikasi, dan sains. Data ini bersifat seed demo.'),
    (11, 'telkom-university', 'Telkom University', 'Bandung', 'Bandung, Jawa Barat', 'https://telkomuniversity.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta yang dikenal pada bidang teknologi informasi, bisnis digital, desain, komunikasi, dan rekayasa.'),
    (12, 'binus-university', 'BINUS University', 'Jakarta dan Tangerang', 'Jakarta, Tangerang, dan beberapa lokasi kampus lain', 'https://binus.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta dengan program populer di bidang komputer, bisnis, desain, komunikasi, dan sistem informasi.'),
    (13, 'universitas-gunadarma', 'Universitas Gunadarma', 'Depok dan Jakarta', 'Depok dan Jakarta', 'https://www.gunadarma.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta yang dikenal pada bidang komputer, ekonomi, psikologi, dan teknik. Data ini digunakan sebagai seed awal.'),
    (14, 'universitas-katolik-indonesia-atma-jaya', 'Universitas Katolik Indonesia Atma Jaya', 'Jakarta', 'Jakarta', 'https://www.atmajaya.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta dengan program di bidang bisnis, psikologi, teknik, pendidikan, dan ilmu kesehatan.'),
    (15, 'universitas-trisakti', 'Universitas Trisakti', 'Jakarta', 'Jakarta Barat, DKI Jakarta', 'https://trisakti.ac.id', 'Perguruan Tinggi Swasta', 'Kampus swasta di Jakarta dengan pilihan program pada teknik, ekonomi, arsitektur, hukum, dan bidang profesional.')
ON DUPLICATE KEY UPDATE
    campus_name = VALUES(campus_name),
    city = VALUES(city),
    address = VALUES(address),
    website = VALUES(website),
    campus_type = VALUES(campus_type),
    description = VALUES(description),
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO study_programs (campus_id, slug, program_name, faculty, degree, accreditation, learning_mode, duration, tuition_range, summary, curriculum_points, career_paths, skills, facilities)
VALUES
    (1, 'teknik-informatika', 'Teknik Informatika', 'Fakultas Ilmu Komputer', 'S1', 'Baik Sekali', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari pemrograman, rekayasa perangkat lunak, jaringan, keamanan, data, dan kecerdasan buatan.', 'Dasar pemrograman;Struktur data;Basis data;Rekayasa perangkat lunak;Kecerdasan buatan', 'Software Developer;Backend Developer;Data Analyst;AI Engineer;System Analyst', 'Problem solving;Logika algoritma;Pemrograman;Analisis data;Kolaborasi', 'Laboratorium komputer;Akses pembelajaran digital;Bimbingan akademik;Kegiatan minat mahasiswa'),
    (1, 'sistem-informasi', 'Sistem Informasi', 'Fakultas Ilmu Komputer', 'S1', 'Baik Sekali', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi yang menghubungkan teknologi, proses bisnis, basis data, analisis sistem, dan kebutuhan organisasi.', 'Analisis proses bisnis;Basis data;Manajemen proyek TI;Enterprise system;UI/UX dasar', 'Business Analyst;System Analyst;IT Project Officer;Product Owner;Database Administrator', 'Analisis kebutuhan;Komunikasi bisnis;Pemodelan sistem;Manajemen data;Dokumentasi', 'Laboratorium komputer;Studi kasus bisnis digital;Simulasi proyek;Akses materi digital'),
    (1, 'manajemen', 'Manajemen', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Baik Sekali', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami pengelolaan organisasi, bisnis, pemasaran, SDM, keuangan, dan strategi.', 'Pengantar manajemen;Pemasaran;Keuangan;SDM;Kewirausahaan', 'Management Trainee;Marketing Officer;HR Officer;Business Development;Entrepreneur', 'Kepemimpinan;Analisis bisnis;Komunikasi;Strategi;Negosiasi', 'Kelas diskusi;Studi kasus bisnis;Kegiatan kewirausahaan;Bimbingan akademik'),
    (1, 'desain-komunikasi-visual', 'Desain Komunikasi Visual', 'Fakultas Desain dan Industri Kreatif', 'S1', 'Dalam verifikasi', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami desain, visual branding, ilustrasi, media digital, dan komunikasi visual.', 'Dasar desain;Tipografi;Ilustrasi digital;Branding;Desain UI', 'Graphic Designer;UI Designer;Brand Designer;Illustrator;Creative Content Designer', 'Kreativitas visual;Komposisi;Software desain;Storytelling visual;Riset pengguna', 'Studio desain;Perangkat desain digital;Galeri karya;Pendampingan portofolio'),
    (1, 'ilmu-komunikasi', 'Ilmu Komunikasi', 'Fakultas Ilmu Komunikasi', 'S1', 'Baik Sekali', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami komunikasi massa, public relations, media digital, konten, dan strategi komunikasi.', 'Dasar komunikasi;Public relations;Komunikasi digital;Produksi konten;Riset media', 'Public Relations Officer;Content Strategist;Social Media Specialist;Media Planner;Communication Officer', 'Public speaking;Menulis;Riset audiens;Produksi konten;Manajemen komunikasi', 'Studio media;Ruang praktik komunikasi;Kegiatan produksi konten;Bimbingan portofolio'),
    (1, 'akuntansi', 'Akuntansi', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Baik Sekali', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari pencatatan keuangan, audit, perpajakan, dan pelaporan bisnis.', 'Akuntansi dasar;Akuntansi keuangan;Perpajakan;Audit;Sistem informasi akuntansi', 'Accounting Staff;Auditor;Tax Officer;Finance Officer;Budget Analyst', 'Ketelitian;Analisis angka;Etika profesi;Pelaporan keuangan;Software akuntansi', 'Laboratorium akuntansi;Studi kasus laporan keuangan;Simulasi pajak;Bimbingan akademik'),
    (2, 'ui-ilmu-komputer', 'Ilmu Komputer', 'Fakultas Ilmu Komputer', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari fondasi komputasi, algoritma, sistem perangkat lunak, data, dan kecerdasan buatan.', 'Algoritma;Matematika diskrit;Sistem operasi;Basis data;Machine learning', 'Software Engineer;Research Assistant;Data Scientist;AI Engineer;Cybersecurity Analyst', 'Pemrograman;Berpikir komputasional;Riset teknis;Analisis sistem;Pemecahan masalah', 'Laboratorium komputer;Komunitas teknologi;Akses riset;Ekosistem akademik besar'),
    (2, 'ui-kedokteran', 'Pendidikan Dokter', 'Fakultas Kedokteran', 'S1', 'Perlu verifikasi LAM-PTKes', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk menyiapkan calon dokter melalui ilmu biomedis, klinik, etika, dan pelayanan kesehatan.', 'Anatomi;Fisiologi;Patologi;Keterampilan klinik;Etika kedokteran', 'Dokter;Peneliti kesehatan;Medical Officer;Akademisi klinik', 'Empati;Analisis klinis;Komunikasi pasien;Ketelitian;Etika profesi', 'Laboratorium biomedis;Rumah sakit pendidikan;Klinik keterampilan;Perpustakaan kesehatan'),
    (2, 'ui-psikologi', 'Psikologi', 'Fakultas Psikologi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami perilaku manusia, proses mental, asesmen psikologi, dan intervensi berbasis ilmu.', 'Psikologi umum;Statistika psikologi;Psikometri;Psikologi perkembangan;Psikologi industri', 'HR Specialist;Konselor lanjutan;Research Assistant;Talent Assessment Officer', 'Observasi;Wawancara;Analisis data;Empati;Etika asesmen', 'Laboratorium psikologi;Ruang observasi;Kegiatan riset;Bimbingan akademik'),
    (2, 'ui-akuntansi', 'Akuntansi', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari akuntansi keuangan, audit, sistem informasi akuntansi, dan pengambilan keputusan bisnis.', 'Akuntansi keuangan;Audit;Perpajakan;Manajemen keuangan;Sistem informasi akuntansi', 'Auditor;Accountant;Tax Consultant;Financial Analyst', 'Analisis laporan;Ketelitian;Etika profesi;Pengolahan data;Problem solving', 'Laboratorium bisnis;Studi kasus perusahaan;Kegiatan organisasi;Akses literatur ekonomi'),
    (3, 'itb-teknik-informatika', 'Teknik Informatika', 'Sekolah Teknik Elektro dan Informatika', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi teknik komputasi yang kuat pada algoritma, sistem perangkat lunak, kecerdasan buatan, dan infrastruktur digital.', 'Algoritma;Pemrograman lanjut;Sistem operasi;Jaringan komputer;AI', 'Software Engineer;AI Engineer;Cybersecurity Engineer;System Architect', 'Logika kuat;Matematika komputasi;Pemrograman;Riset teknis;Kolaborasi proyek', 'Laboratorium komputasi;Ekosistem teknologi;Komunitas riset;Project-based learning'),
    (3, 'itb-teknik-elektro', 'Teknik Elektro', 'Sekolah Teknik Elektro dan Informatika', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami elektronika, sistem tenaga, telekomunikasi, kontrol, dan teknologi perangkat keras.', 'Rangkaian listrik;Elektronika;Sistem kontrol;Telekomunikasi;Sinyal dan sistem', 'Electrical Engineer;Control Engineer;Telecommunication Engineer;Hardware Engineer', 'Analisis rangkaian;Matematika teknik;Eksperimen;Desain sistem;Pemecahan masalah', 'Laboratorium elektro;Proyek rekayasa;Peralatan praktikum;Komunitas teknologi'),
    (3, 'itb-teknik-sipil', 'Teknik Sipil', 'Fakultas Teknik Sipil dan Lingkungan', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang, membangun, dan mengelola infrastruktur seperti gedung, jalan, jembatan, dan air.', 'Mekanika teknik;Struktur beton;Transportasi;Geoteknik;Manajemen konstruksi', 'Civil Engineer;Site Engineer;Structural Engineer;Project Engineer', 'Analisis struktur;Manajemen proyek;Ketelitian;Pengukuran lapangan;Software teknik', 'Laboratorium struktur;Laboratorium tanah;Praktik lapangan;Studio perancangan'),
    (3, 'itb-desain-produk', 'Desain Produk', 'Fakultas Seni Rupa dan Desain', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang produk yang fungsional, estetis, ergonomis, dan sesuai kebutuhan pengguna.', 'Dasar desain;Ergonomi;Material produk;Prototyping;Desain berkelanjutan', 'Product Designer;Industrial Designer;UX Designer;Design Researcher', 'Riset pengguna;Sketsa;Prototyping;Kreativitas;Pemecahan masalah', 'Studio desain;Workshop prototipe;Galeri karya;Peralatan produksi'),
    (4, 'ugm-kedokteran', 'Pendidikan Dokter', 'Fakultas Kedokteran, Kesehatan Masyarakat, dan Keperawatan', 'S1', 'Perlu verifikasi LAM-PTKes', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk menyiapkan calon dokter dengan dasar biomedis, klinik, kesehatan masyarakat, dan etika profesi.', 'Biomedis;Anatomi;Keterampilan klinik;Patologi;Ilmu kesehatan masyarakat', 'Dokter;Medical Officer;Peneliti kesehatan;Akademisi klinik', 'Komunikasi pasien;Analisis klinis;Empati;Etika profesi;Kerja tim', 'Laboratorium medis;Rumah sakit pendidikan;Klinik keterampilan;Lingkungan riset'),
    (4, 'ugm-hukum', 'Ilmu Hukum', 'Fakultas Hukum', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami sistem hukum, peraturan, argumentasi hukum, kontrak, dan penyelesaian sengketa.', 'Pengantar hukum;Hukum pidana;Hukum perdata;Hukum tata negara;Metode penelitian hukum', 'Legal Officer;Advokat setelah pendidikan profesi;Policy Analyst;Compliance Officer', 'Argumentasi;Analisis peraturan;Menulis hukum;Negosiasi;Etika profesi', 'Moot court;Perpustakaan hukum;Klinik hukum;Diskusi kasus'),
    (4, 'ugm-manajemen', 'Manajemen', 'Fakultas Ekonomika dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari pengelolaan bisnis, strategi, pemasaran, keuangan, operasi, dan SDM.', 'Manajemen dasar;Keuangan;Pemasaran;Operasi;Strategi bisnis', 'Management Trainee;Business Analyst;Marketing Strategist;Entrepreneur', 'Analisis bisnis;Komunikasi;Kepemimpinan;Pengambilan keputusan;Kolaborasi', 'Laboratorium bisnis;Studi kasus;Komunitas kewirausahaan;Akses riset ekonomi'),
    (4, 'ugm-ilmu-komputer', 'Ilmu Komputer', 'Fakultas Matematika dan Ilmu Pengetahuan Alam', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi komputasi untuk mempelajari algoritma, pemrograman, basis data, AI, dan komputasi ilmiah.', 'Pemrograman;Algoritma;Basis data;Komputasi ilmiah;Machine learning', 'Software Developer;Data Analyst;AI Engineer;Research Assistant', 'Logika komputasi;Analisis data;Pemrograman;Pemodelan;Riset', 'Laboratorium komputer;Kegiatan riset;Komunitas teknologi;Akses literatur'),
    (5, 'ipb-agribisnis', 'Agribisnis', 'Fakultas Ekonomi dan Manajemen', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari bisnis pertanian, rantai pasok pangan, pemasaran agribisnis, dan kewirausahaan.', 'Ekonomi pertanian;Pemasaran agribisnis;Rantai pasok;Kewirausahaan;Manajemen usaha tani', 'Agribusiness Analyst;Supply Chain Officer;Business Development;Entrepreneur pangan', 'Analisis pasar;Manajemen rantai pasok;Komunikasi bisnis;Riset lapangan;Kewirausahaan', 'Laboratorium bisnis;Kebun praktik;Studi lapangan;Inkubasi bisnis'),
    (5, 'ipb-teknologi-pangan', 'Teknologi Pangan', 'Fakultas Teknologi Pertanian', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami pengolahan pangan, keamanan pangan, mutu, inovasi produk, dan teknologi industri pangan.', 'Kimia pangan;Mikrobiologi pangan;Teknologi proses;Keamanan pangan;Pengendalian mutu', 'Food Technologist;Quality Control;R&D Product;Food Safety Officer', 'Analisis laboratorium;Ketelitian;Inovasi produk;Higiene pangan;Problem solving', 'Laboratorium pangan;Pilot plant;Praktikum mutu;Riset produk'),
    (5, 'ipb-ilmu-gizi', 'Ilmu Gizi', 'Fakultas Ekologi Manusia', 'S1', 'Perlu verifikasi LAM-PTKes', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari gizi manusia, dietetik, kesehatan masyarakat, pangan, dan intervensi gizi.', 'Dasar gizi;Dietetik;Biokimia gizi;Gizi masyarakat;Penilaian status gizi', 'Nutritionist;Dietitian setelah pendidikan profesi;Food Service Officer;Community Nutrition Officer', 'Komunikasi kesehatan;Analisis gizi;Empati;Edukasi masyarakat;Riset data', 'Laboratorium gizi;Praktik komunitas;Klinik pembelajaran;Kegiatan edukasi'),
    (6, 'its-sistem-informasi', 'Sistem Informasi', 'Fakultas Teknologi Elektro dan Informatika Cerdas', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk menggabungkan teknologi, bisnis, data, analisis proses, dan transformasi digital organisasi.', 'Analisis sistem;Basis data;Manajemen proyek TI;Data analytics;Enterprise architecture', 'Business Analyst;Data Analyst;IT Consultant;Product Owner', 'Analisis kebutuhan;Manajemen data;Komunikasi bisnis;Dokumentasi;Kolaborasi', 'Laboratorium SI;Proyek industri;Komunitas teknologi;Studi kasus digital'),
    (6, 'its-teknik-informatika', 'Teknik Informatika', 'Fakultas Teknologi Elektro dan Informatika Cerdas', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi teknik komputasi untuk pemrograman, AI, jaringan, keamanan, dan rekayasa perangkat lunak.', 'Algoritma;Pemrograman lanjut;Basis data;Jaringan;AI', 'Software Engineer;Backend Developer;AI Engineer;Cybersecurity Analyst', 'Pemrograman;Analisis sistem;Matematika komputasi;Problem solving;Kerja tim', 'Laboratorium komputer;Proyek perangkat lunak;Komunitas riset;Akses pembelajaran'),
    (6, 'its-teknik-industri', 'Teknik Industri', 'Fakultas Teknologi Industri dan Rekayasa Sistem', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang sistem kerja, produksi, rantai pasok, optimasi, dan peningkatan produktivitas.', 'Statistika industri;Ergonomi;Riset operasi;Manajemen produksi;Supply chain', 'Industrial Engineer;Process Improvement Analyst;Supply Chain Planner;Operations Analyst', 'Optimasi;Analisis proses;Pemodelan sistem;Manajemen proyek;Komunikasi', 'Laboratorium ergonomi;Simulasi industri;Studi lapangan;Software optimasi'),
    (7, 'unair-farmasi', 'Farmasi', 'Fakultas Farmasi', 'S1', 'Perlu verifikasi LAM-PTKes', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari obat, formulasi, farmakologi, pelayanan kefarmasian, dan pengembangan produk kesehatan.', 'Kimia farmasi;Farmakologi;Teknologi sediaan;Farmasi klinik;Regulasi obat', 'Pharmacist setelah profesi;R&D Farmasi;Quality Assurance;Regulatory Affairs', 'Ketelitian;Analisis laboratorium;Etika kesehatan;Komunikasi pasien;Riset', 'Laboratorium farmasi;Praktikum formulasi;Fasilitas riset;Kerja sama kesehatan'),
    (7, 'unair-kesehatan-masyarakat', 'Kesehatan Masyarakat', 'Fakultas Kesehatan Masyarakat', 'S1', 'Perlu verifikasi LAM-PTKes', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami epidemiologi, promosi kesehatan, kebijakan, keselamatan kerja, dan kesehatan lingkungan.', 'Epidemiologi;Biostatistika;Promosi kesehatan;K3;Kesehatan lingkungan', 'Public Health Officer;Health Promoter;Epidemiology Assistant;K3 Officer', 'Analisis data;Komunikasi masyarakat;Riset lapangan;Perencanaan program;Advokasi', 'Laboratorium kesehatan;Praktik komunitas;Riset lapangan;Kegiatan edukasi'),
    (7, 'unair-manajemen', 'Manajemen', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi bisnis untuk strategi, pemasaran, operasi, keuangan, organisasi, dan kewirausahaan.', 'Manajemen dasar;Keuangan;Pemasaran;Operasi;Kewirausahaan', 'Management Trainee;Marketing Officer;Business Analyst;Entrepreneur', 'Kepemimpinan;Analisis pasar;Komunikasi;Pengambilan keputusan;Negosiasi', 'Laboratorium bisnis;Studi kasus;Kegiatan kewirausahaan;Komunitas mahasiswa'),
    (8, 'undip-teknik-sipil', 'Teknik Sipil', 'Fakultas Teknik', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang dan mengelola infrastruktur bangunan, jalan, jembatan, air, dan proyek konstruksi.', 'Mekanika teknik;Struktur;Hidrologi;Transportasi;Manajemen konstruksi', 'Civil Engineer;Structural Engineer;Site Engineer;Project Planner', 'Analisis struktur;Pengukuran;Manajemen proyek;Software teknik;Ketelitian', 'Laboratorium struktur;Laboratorium tanah;Studio perancangan;Praktik lapangan'),
    (8, 'undip-ilmu-komunikasi', 'Ilmu Komunikasi', 'Fakultas Ilmu Sosial dan Ilmu Politik', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari komunikasi strategis, media, public relations, riset audiens, dan komunikasi digital.', 'Teori komunikasi;Public relations;Media digital;Riset komunikasi;Produksi konten', 'PR Officer;Content Strategist;Media Planner;Communication Analyst', 'Menulis;Public speaking;Riset audiens;Produksi konten;Strategi komunikasi', 'Studio komunikasi;Kegiatan media;Diskusi kasus;Praktik produksi'),
    (8, 'undip-akuntansi', 'Akuntansi', 'Fakultas Ekonomika dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari laporan keuangan, audit, perpajakan, sistem informasi akuntansi, dan tata kelola.', 'Akuntansi keuangan;Audit;Perpajakan;Akuntansi manajemen;SIA', 'Auditor;Accountant;Tax Officer;Finance Analyst', 'Ketelitian;Analisis angka;Etika;Pelaporan;Pengolahan data', 'Laboratorium akuntansi;Studi kasus perusahaan;Simulasi laporan;Akses literatur'),
    (9, 'ub-administrasi-bisnis', 'Ilmu Administrasi Bisnis', 'Fakultas Ilmu Administrasi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami organisasi bisnis, pemasaran, kewirausahaan, administrasi perusahaan, dan strategi layanan.', 'Administrasi bisnis;Pemasaran;Keuangan bisnis;Kewirausahaan;Perilaku organisasi', 'Business Development;Marketing Officer;Operations Staff;Entrepreneur', 'Komunikasi bisnis;Analisis pasar;Manajemen proses;Negosiasi;Perencanaan', 'Laboratorium bisnis;Studi kasus;Kegiatan kewirausahaan;Diskusi proyek'),
    (9, 'ub-teknik-informatika', 'Teknik Informatika', 'Fakultas Ilmu Komputer', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari sistem komputasi, pemrograman, data, perangkat lunak, dan teknologi cerdas.', 'Pemrograman;Basis data;Jaringan;Rekayasa perangkat lunak;AI', 'Software Developer;Data Analyst;Backend Developer;System Analyst', 'Pemrograman;Analisis masalah;Logika komputasi;Kolaborasi;Riset teknis', 'Laboratorium komputer;Proyek teknologi;Komunitas IT;Kegiatan riset'),
    (9, 'ub-manajemen', 'Manajemen', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami fungsi bisnis, strategi, keuangan, pemasaran, SDM, dan kewirausahaan.', 'Manajemen dasar;Keuangan;Pemasaran;SDM;Strategi', 'Management Trainee;Business Analyst;HR Officer;Entrepreneur', 'Leadership;Analisis bisnis;Komunikasi;Strategi;Problem solving', 'Laboratorium bisnis;Studi kasus;Komunitas kewirausahaan;Bimbingan akademik'),
    (10, 'unpad-ilmu-komunikasi', 'Ilmu Komunikasi', 'Fakultas Ilmu Komunikasi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari public relations, jurnalistik, komunikasi digital, media, dan riset komunikasi.', 'Teori komunikasi;Jurnalistik;Public relations;Komunikasi digital;Riset komunikasi', 'PR Officer;Journalist;Content Strategist;Media Analyst', 'Menulis;Public speaking;Riset audiens;Produksi media;Strategi pesan', 'Studio komunikasi;Praktik media;Kegiatan produksi;Diskusi kasus'),
    (10, 'unpad-psikologi', 'Psikologi', 'Fakultas Psikologi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami perilaku, proses mental, asesmen, perkembangan, organisasi, dan kesehatan mental.', 'Psikologi umum;Psikometri;Psikologi perkembangan;Psikologi sosial;Metode riset', 'HR Specialist;Research Assistant;Talent Assessment Officer;Konselor setelah pendidikan lanjut', 'Observasi;Wawancara;Analisis data;Empati;Etika', 'Laboratorium psikologi;Ruang observasi;Riset lapangan;Bimbingan akademik'),
    (10, 'unpad-hukum', 'Ilmu Hukum', 'Fakultas Hukum', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami prinsip hukum, kontrak, litigasi, kebijakan publik, dan tata kelola.', 'Pengantar hukum;Hukum pidana;Hukum perdata;Hukum bisnis;Metode riset hukum', 'Legal Officer;Compliance Staff;Policy Analyst;Advokat setelah profesi', 'Argumentasi;Analisis peraturan;Menulis hukum;Negosiasi;Etika', 'Moot court;Perpustakaan hukum;Klinik hukum;Diskusi kasus'),
    (11, 'telkom-informatika', 'Informatika', 'Fakultas Informatika', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi teknologi untuk pemrograman, data, cloud, AI, keamanan, dan pengembangan produk digital.', 'Pemrograman;Algoritma;Cloud computing;Data science;Keamanan siber', 'Software Engineer;Cloud Engineer;AI Engineer;Security Analyst', 'Pemrograman;Problem solving;Analisis data;Kolaborasi agile;Riset produk', 'Laboratorium IT;Proyek industri;Komunitas startup;Infrastruktur digital'),
    (11, 'telkom-sistem-informasi', 'Sistem Informasi', 'Fakultas Rekayasa Industri', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi yang menghubungkan sistem digital, proses bisnis, data, manajemen proyek, dan inovasi layanan.', 'Analisis sistem;Proses bisnis;Basis data;Manajemen proyek;Data analytics', 'Business Analyst;Product Owner;IT Consultant;Data Analyst', 'Komunikasi bisnis;Analisis data;Dokumentasi;Agile teamwork;Problem solving', 'Laboratorium SI;Project-based learning;Studi kasus industri;Ekosistem digital'),
    (11, 'telkom-dkv', 'Desain Komunikasi Visual', 'Fakultas Industri Kreatif', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi desain untuk branding, UI, ilustrasi, animasi, media kreatif, dan komunikasi visual digital.', 'Dasar desain;Brand identity;Tipografi;Ilustrasi;Desain interaktif', 'Graphic Designer;UI Designer;Brand Designer;Motion Designer', 'Kreativitas;Software desain;Riset visual;Storytelling;Portofolio', 'Studio desain;Workshop kreatif;Galeri karya;Komunitas kreatif'),
    (12, 'binus-computer-science', 'Computer Science', 'School of Computer Science', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi komputer untuk software engineering, AI, data, web, mobile, dan teknologi digital.', 'Programming;Data structures;Software engineering;AI;Database systems', 'Software Engineer;Mobile Developer;AI Engineer;Data Analyst', 'Coding;Computational thinking;Team project;Problem solving;Product thinking', 'Computer lab;Industry project;Innovation ecosystem;Digital learning'),
    (12, 'binus-information-systems', 'Information Systems', 'School of Information Systems', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk menggabungkan teknologi, bisnis, enterprise system, data, dan transformasi digital.', 'Business process;Database;Enterprise system;Project management;Data analytics', 'System Analyst;Business Analyst;IT Consultant;Product Owner', 'Business analysis;Documentation;Data management;Communication;Agile collaboration', 'IS lab;Case-based learning;Industry collaboration;Digital platform'),
    (12, 'binus-vcd', 'Visual Communication Design', 'School of Design', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi desain visual untuk branding, media digital, ilustrasi, UI, dan komunikasi kreatif.', 'Design principles;Typography;Branding;Digital illustration;UI design', 'Graphic Designer;Brand Designer;UI Designer;Creative Designer', 'Visual thinking;Design software;Creative research;Composition;Portfolio building', 'Design studio;Creative lab;Portfolio mentoring;Exhibition activities'),
    (13, 'gunadarma-sistem-informasi', 'Sistem Informasi', 'Fakultas Ilmu Komputer dan Teknologi Informasi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari analisis sistem, basis data, pemrograman, bisnis, dan implementasi sistem informasi.', 'Basis data;Analisis sistem;Pemrograman;Manajemen proyek;Sistem enterprise', 'System Analyst;IT Support Analyst;Business Analyst;Database Officer', 'Analisis kebutuhan;Pemrograman dasar;Dokumentasi;Data handling;Komunikasi', 'Laboratorium komputer;Kegiatan praktikum;Proyek sistem;Akses materi digital'),
    (13, 'gunadarma-teknik-informatika', 'Teknik Informatika', 'Fakultas Teknologi Industri', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mengembangkan kemampuan pemrograman, jaringan, perangkat lunak, database, dan teknologi komputasi.', 'Algoritma;Pemrograman;Basis data;Jaringan komputer;Rekayasa perangkat lunak', 'Programmer;Software Developer;Network Support;System Analyst', 'Coding;Problem solving;Analisis sistem;Kerja tim;Ketelitian', 'Laboratorium komputer;Praktikum jaringan;Proyek aplikasi;Kegiatan IT'),
    (13, 'gunadarma-psikologi', 'Psikologi', 'Fakultas Psikologi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk mempelajari perilaku, perkembangan, psikometri, industri organisasi, dan riset psikologi.', 'Psikologi umum;Psikometri;Perkembangan;Sosial;Industri organisasi', 'HR Staff;Talent Assessment;Research Assistant;Konselor setelah studi lanjut', 'Observasi;Wawancara;Empati;Analisis data;Etika', 'Laboratorium psikologi;Ruang observasi;Kegiatan riset;Diskusi kasus'),
    (14, 'atma-psikologi', 'Psikologi', 'Fakultas Psikologi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami perilaku manusia, asesmen, perkembangan, kesehatan mental, dan psikologi organisasi.', 'Psikologi dasar;Psikometri;Konseling dasar;Psikologi industri;Metode riset', 'HR Specialist;Research Assistant;Talent Officer;Konselor setelah pendidikan lanjut', 'Empati;Observasi;Analisis data;Komunikasi;Etika', 'Laboratorium psikologi;Kegiatan riset;Diskusi kasus;Bimbingan akademik'),
    (14, 'atma-teknik-industri', 'Teknik Industri', 'Fakultas Teknik', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang sistem produksi, layanan, optimasi proses, ergonomi, dan rantai pasok.', 'Riset operasi;Ergonomi;Manajemen produksi;Statistika;Supply chain', 'Industrial Engineer;Process Analyst;Production Planner;Supply Chain Officer', 'Optimasi;Analisis proses;Manajemen proyek;Komunikasi;Data analysis', 'Laboratorium teknik industri;Simulasi sistem;Proyek industri;Studi kasus'),
    (14, 'atma-akuntansi', 'Akuntansi', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami akuntansi, audit, perpajakan, pelaporan keuangan, dan tata kelola bisnis.', 'Akuntansi keuangan;Audit;Pajak;Akuntansi manajemen;SIA', 'Auditor;Accountant;Tax Officer;Financial Staff', 'Ketelitian;Analisis angka;Etika;Pelaporan;Komunikasi bisnis', 'Laboratorium bisnis;Studi kasus keuangan;Diskusi profesional;Akses literatur'),
    (15, 'trisakti-arsitektur', 'Arsitektur', 'Fakultas Teknik Sipil dan Perencanaan', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk merancang bangunan, ruang, lingkungan, konsep desain, dan gambar teknis arsitektur.', 'Studio desain;Struktur bangunan;Sejarah arsitektur;Perancangan kota;Teknologi bangunan', 'Architect setelah profesi;Interior Designer;Urban Design Assistant;Drafter', 'Sketsa;Perancangan ruang;Software desain;Kreativitas;Presentasi visual', 'Studio arsitektur;Workshop maket;Ruang presentasi;Praktik desain'),
    (15, 'trisakti-teknik-perminyakan', 'Teknik Perminyakan', 'Fakultas Teknologi Kebumian dan Energi', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi untuk memahami eksplorasi, produksi, reservoir, pengeboran, dan pengelolaan energi migas.', 'Geologi dasar;Reservoir;Pengeboran;Produksi migas;Manajemen energi', 'Petroleum Engineer;Drilling Engineer;Reservoir Analyst;Energy Analyst', 'Analisis data teknis;Matematika teknik;Keselamatan kerja;Problem solving;Kerja lapangan', 'Laboratorium kebumian;Simulasi reservoir;Praktik lapangan;Kegiatan industri'),
    (15, 'trisakti-manajemen', 'Manajemen', 'Fakultas Ekonomi dan Bisnis', 'S1', 'Perlu verifikasi BAN-PT/LAM', 'Reguler', '8 Semester', 'Cek laman resmi kampus untuk biaya terbaru', 'Program studi bisnis untuk memahami pemasaran, keuangan, SDM, operasi, strategi, dan kewirausahaan.', 'Manajemen dasar;Pemasaran;Keuangan;SDM;Kewirausahaan', 'Management Trainee;Marketing Officer;Business Analyst;Entrepreneur', 'Leadership;Komunikasi;Analisis bisnis;Strategi;Negosiasi', 'Laboratorium bisnis;Studi kasus;Kegiatan wirausaha;Bimbingan akademik')
ON DUPLICATE KEY UPDATE
    campus_id = VALUES(campus_id),
    program_name = VALUES(program_name),
    faculty = VALUES(faculty),
    degree = VALUES(degree),
    accreditation = VALUES(accreditation),
    learning_mode = VALUES(learning_mode),
    duration = VALUES(duration),
    tuition_range = VALUES(tuition_range),
    summary = VALUES(summary),
    curriculum_points = VALUES(curriculum_points),
    career_paths = VALUES(career_paths),
    skills = VALUES(skills),
    facilities = VALUES(facilities),
    is_active = 1,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW campus_program_overview AS
SELECT sp.id, sp.slug AS program_slug, sp.program_name, sp.faculty, sp.degree, sp.accreditation, sp.learning_mode, sp.duration, c.campus_name, c.city, c.campus_type
FROM study_programs sp INNER JOIN campuses c ON c.id = sp.campus_id WHERE sp.is_active = 1;

SELECT COUNT(*) AS total_kampus FROM campuses;
SELECT COUNT(*) AS total_prodi FROM study_programs WHERE is_active = 1;